version: '3.8'

services:
  # Local S3-compatible MinIO server
  minio:
    image: minio/minio:latest
    container_name: common-minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Auto-creates default S3 bucket
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadminpassword;
      /usr/bin/mc mb myminio/accurex-media --ignore-existing;
      /usr/bin/mc anonymous set download myminio/accurex-media;
      exit 0;
      "

  # Local RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: common-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  minio_data:
  rabbitmq_data:
